import { Icon } from "@/components/icon";
import Link from "next/link";
import { getDb } from "@/lib/db";
import { requireSessionUser } from "@/lib/auth";
import { saveMonthlyReview } from "@/lib/actions";
import { getMonthlyPlan } from "@/lib/plan";
import { getMonthlyWorkObjectives, objectiveProgress } from "@/lib/planning";

type Review = { manager_comments: string; manager_rating: number | null; status: string; objective_outcome: string; key_achievements: string; outputs_delivered: string; impact_summary: string; recommendations: string; pending_items: string; self_rating: number | null };
type Work = { title: string; description: string; work_type: "planned" | "recurring" | "reactive"; status: string; created_at: string };
const monthName = (month: number) => new Intl.DateTimeFormat("en-GB", { month: "long" }).format(new Date(2025, month - 1, 1));

export default async function ReviewsPage({ searchParams }: { searchParams: Promise<{ year?: string; month?: string; saved?: string }> }) {
  const user = await requireSessionUser(); const params = await searchParams; const now = new Date(); const year = Number(params.year) || now.getFullYear(); const month = Number(params.month) || now.getMonth() + 1; const db = getDb();
  const plan = getMonthlyPlan(user.id, year, month); const objectives = plan ? getMonthlyWorkObjectives(plan.id) : [];
  const review = db.prepare("SELECT status, objective_outcome, key_achievements, outputs_delivered, impact_summary, recommendations, pending_items, self_rating, manager_comments, manager_rating FROM monthly_reviews WHERE user_id = ? AND year = ? AND month = ?").get(user.id, year, month) as Review | undefined;
  const work = db.prepare("SELECT title, description, work_type, status, created_at FROM work_items WHERE user_id = ? AND substr(created_at, 1, 7) = ? AND status != 'cancelled' ORDER BY created_at DESC").all(user.id, `${year}-${String(month).padStart(2, "0")}`) as Work[];
  const completed = work.filter((item) => item.status === "completed"); const totals = ["planned", "recurring", "reactive"].map((type) => work.filter((item) => item.work_type === type).length);
  const objectiveRows = objectives.map((objective) => ({ title: objective.title, strategic: objective.strategic_titles || "Strategic alignment", percent: objectiveProgress(objective) }));
  const overall = objectiveRows.length ? Math.round(objectiveRows.reduce((sum, item) => sum + item.percent, 0) / objectiveRows.length) : 0;
  const previous = month === 1 ? { year: year - 1, month: 12 } : { year, month: month - 1 }; const next = month === 12 ? { year: year + 1, month: 1 } : { year, month: month + 1 };
  const locked = review?.status === "reviewed";
  return <div className="space-y-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-[40px] font-bold leading-none tracking-[-.045em] text-slate-950">Monthly Review</h1><p className="mt-2 text-[17px] text-slate-500">This review is auto-generated from your activities, objectives and reports. Add your reflections and submit for review.</p></div><div className="flex flex-wrap items-center gap-2"><Link href={`/reviews?year=${previous.year}&month=${previous.month}`} className="rounded-lg border border-slate-200 px-4 py-2 text-blue-600" aria-label="Previous month"><Icon name="left" className="h-4 w-4" /></Link><span className="rounded-lg border border-slate-200 bg-white px-4 py-2 text-sm font-semibold">{monthName(month)} {year}　<Icon name="down" className="h-4 w-4" /></span><Link href={`/reviews?year=${next.year}&month=${next.month}`} className="rounded-lg border border-slate-200 px-4 py-2 text-blue-600" aria-label="Next month"><Icon name="right" className="h-4 w-4" /></Link><span className={`rounded-lg px-3 py-2 text-xs font-semibold ${review?.status === "submitted" ? "bg-blue-50 text-blue-700" : review?.status === "reviewed" ? "bg-emerald-50 text-emerald-700" : "bg-emerald-50 text-emerald-700"}`}>● {review?.status === "submitted" ? "Submitted" : review?.status === "reviewed" ? "Reviewed" : "Draft"}</span></div></div>
    {params.saved === "1" && <div className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800">Monthly review saved.</div>}
    <div className="flex items-center gap-4 overflow-x-auto"><Step number="1" title="Review Progress" text="Check your auto-generated summary" active /><Step number="2" title="Add Reflection" text="Share your thoughts and insights" /><Step number="3" title="Submit" text="Send to your manager for review" /></div>
    <form action={saveMonthlyReview} className="grid gap-5 xl:grid-cols-[minmax(0,1.7fr)_minmax(330px,1fr)]"><input type="hidden" name="year" value={year} /><input type="hidden" name="month" value={month} /><input type="hidden" name="strategic_objectives" value={objectiveRows.map((item) => item.title).join("; ")} /><input type="hidden" name="outputs_delivered" value={completed.map((item) => item.title).join("; ")} /><fieldset disabled={locked} className="contents"><main className="space-y-4"><section className="rounded-xl border border-slate-200 bg-white p-5"><div className="flex items-center justify-between"><div><h2 className="text-xl font-bold text-slate-950">Objectives Progress</h2><p className="mt-1 text-sm text-slate-500">Progress on your {objectiveRows.length} active objectives this month.</p></div><Link href="/monthly" className="text-sm font-medium text-blue-600">View all objectives <Icon name="arrow" className="h-4 w-4" /></Link></div><div className="mt-5 flex flex-col gap-5 lg:flex-row"><div className="flex h-40 w-40 shrink-0 items-center justify-center rounded-full border-[16px] border-blue-600"><div className="text-center"><strong className="block text-3xl text-slate-950">{overall}%</strong><span className="text-xs text-slate-500">Overall progress</span></div></div><div className="flex-1 space-y-4">{objectiveRows.length ? objectiveRows.map((item, index) => <div key={item.title} className="flex gap-3"><i className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-xl not-italic ${index % 3 === 0 ? "bg-blue-50 text-blue-600" : index % 3 === 1 ? "bg-violet-50 text-violet-600" : "bg-emerald-50 text-emerald-600"}`}><Icon name="target" className="h-6 w-6" /></i><div className="min-w-0 flex-1"><strong className="block text-sm text-slate-900">{item.title}</strong><span className="text-xs text-slate-500">{item.strategic}</span><div className="mt-2 h-3 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-blue-600" style={{ width: `${item.percent}%` }} /></div></div><strong className="text-sm text-slate-800">{item.percent}%</strong></div>) : <p className="text-sm text-slate-500">Set monthly objectives to generate your progress summary.</p>}</div></div></section>
      <section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="text-xl font-bold text-slate-950">Activity Breakdown</h2><p className="mt-1 text-sm text-slate-500">Your work activity this month, automatically categorised from tasks and reports.</p><div className="mt-5 grid gap-4 sm:grid-cols-3">{["Planned Tasks", "Recurring Tasks", "Reactive Tasks"].map((name, index) => <div key={name} className="border-r border-slate-100 last:border-0"><div className="flex gap-3"><i className={`flex h-11 w-11 items-center justify-center rounded-xl not-italic ${index === 0 ? "bg-blue-600 text-white" : index === 1 ? "bg-violet-600 text-white" : "bg-red-500 text-white"}`}><Icon name={index === 0 ? "calendar" : index === 1 ? "cycle" : "bolt"} className="h-6 w-6" /></i><div><strong className="block text-sm text-slate-900">{name}</strong><span className="text-xs text-slate-500">{index === 0 ? "Tasks you planned" : index === 1 ? "Regular and ongoing activities" : "Unplanned or ad-hoc work"}</span></div></div><strong className="mt-4 block text-3xl text-slate-950">{totals[index]}</strong><div className="mt-3 h-3 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full ${index === 0 ? "bg-blue-600" : index === 1 ? "bg-violet-600" : "bg-red-500"}`} style={{ width: `${work.length ? (totals[index] / work.length) * 100 : 0}%` }} /></div></div>)}</div></section>
      <section className="rounded-xl border border-slate-200 bg-white p-5"><div className="flex justify-between"><div><h2 className="text-xl font-bold text-slate-950">Key Achievements</h2><p className="mt-1 text-sm text-slate-500">Highlights automatically identified from your activity, objectives and reports.</p></div><Link href="/daily/updates" className="text-sm font-medium text-blue-600">View all activity <Icon name="arrow" className="h-4 w-4" /></Link></div><div className="mt-5 space-y-4">{completed.length ? completed.slice(0, 4).map((item, index) => <div key={item.title} className="flex gap-3"><i className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-xl not-italic ${index % 3 === 0 ? "bg-emerald-50 text-emerald-600" : index % 3 === 1 ? "bg-violet-50 text-violet-600" : "bg-blue-50 text-blue-600"}`}><Icon name="tick" className="h-5 w-5" /></i><span><strong className="block text-sm text-slate-900">{item.title}</strong><span className="block text-sm text-slate-500">{item.description || "Completed work contributing to your monthly objectives."}</span></span></div>) : <p className="py-5 text-sm text-slate-500">Completed work will appear here as monthly achievements.</p>}</div></section></main>
      <aside className="space-y-4"><section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="text-xl font-bold text-slate-950"><Icon name="sparkle" className="h-6 w-6" />　Your Reflection</h2><p className="mt-2 text-sm leading-5 text-slate-500">Share your thoughts on this month&apos;s progress, including challenges, learning, and areas for next month.</p><textarea name="objective_outcome" defaultValue={review?.objective_outcome} rows={9} className="mt-5 w-full rounded-xl border border-slate-200 p-4 text-sm outline-none placeholder:text-slate-400 focus:border-blue-500" placeholder={"What went well this month?\n\nWhat were the key challenges?\n\nWhat did you learn?\n\nWhat are your priorities for next month?"} /><textarea name="key_achievements" defaultValue={review?.key_achievements} className="hidden" /><textarea name="impact_summary" defaultValue={review?.impact_summary} className="hidden" /><textarea name="recommendations" defaultValue={review?.recommendations} className="hidden" /><textarea name="pending_items" defaultValue={review?.pending_items} className="hidden" /><select name="self_rating" defaultValue={review?.self_rating ?? ""} className="mt-3 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm"><option value="">Optional self-rating</option>{[1,2,3,4,5].map((n) => <option key={n} value={n}>{n}/5</option>)}</select></section><section className="rounded-xl border border-blue-100 bg-blue-50 p-5"><h2 className="font-semibold text-blue-700"><Icon name="sun" className="h-6 w-6" />　This review is auto-generated</h2><p className="mt-2 text-sm leading-5 text-slate-600">Your objectives, activities and reports from {monthName(month)} {year} have been analysed to create this summary. You can add your own reflections, and then submit for review.</p></section><section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="text-xl font-bold text-slate-950">Next steps</h2><p className="mt-2 text-sm leading-5 text-slate-500">Once you&apos;re happy with your reflections, submit this review to your manager. You can save a draft and come back to it later.</p>{!locked && <div className="mt-4 space-y-3"><button name="intent" value="draft" className="w-full rounded-lg border border-slate-200 bg-white py-3 text-sm font-semibold text-slate-700"><Icon name="save" className="h-4 w-4" />　Save draft</button><button name="intent" value="submit" className="w-full rounded-lg bg-blue-600 py-3 text-sm font-semibold text-white"><Icon name="send" className="h-4 w-4" />　Submit for review</button></div>}{locked && <p className="mt-4 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-700">This review has been signed off by your manager.</p>}{review?.manager_comments && <p className="mt-4 rounded-lg bg-blue-50 p-3 text-sm text-blue-800">Manager feedback: {review.manager_comments} · Rating: {review.manager_rating ?? "—"}/5</p>}</section></aside></fieldset></form>
  </div>;
}
function Step({ number, title, text, active = false }: { number: string; title: string; text: string; active?: boolean }) { return <div className="flex min-w-72 items-center gap-3"><span className={`flex h-11 w-11 items-center justify-center rounded-full border text-lg font-semibold ${active ? "border-blue-600 bg-blue-600 text-white" : "border-slate-300 text-slate-500"}`}>{number}</span><span><strong className="block text-sm text-slate-900">{title}</strong><span className="text-xs text-slate-500">{text}</span></span></div>; }
