import { Icon } from "@/components/icon";
import { PasswordInput } from "@/components/password-input";
import { redirect } from "next/navigation";
import { login } from "@/lib/actions";
import { getSessionUser } from "@/lib/auth";
import { inputCls, btnPrimary } from "@/components/ui";

function Mark({ small = false }: { small?: boolean }) {
  return <span className={`relative flex items-center justify-center rounded-xl bg-blue-600 font-bold text-white shadow-sm before:absolute before:left-0 before:top-0 before:rounded-tl-xl before:bg-cyan-300 ${small ? "h-8 w-8 text-sm before:h-3.5 before:w-3.5" : "h-11 w-11 text-xl before:h-5 before:w-5"}`}>P</span>;
}


export default async function LoginPage({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
  const user = await getSessionUser(); if (user) redirect("/"); const params = await searchParams;
  return <main className="min-h-screen bg-white"><header className="flex h-[73px] items-center justify-between border-b border-slate-200 px-7"><div className="flex items-center gap-3"><Mark small /><span className="text-[26px] font-bold tracking-[-0.04em] text-slate-950">Progress</span></div><span className="rounded-xl bg-slate-100 p-3 text-amber-500"><Icon name="sun" className="h-5 w-5" /></span></header><div className="grid min-h-[calc(100vh-73px)] lg:grid-cols-2"><section className="relative hidden overflow-hidden lg:block" style={{ backgroundImage: "url('/login-office-hero.png')", backgroundPosition: "center", backgroundSize: "cover" }}><div className="absolute inset-0 bg-white/35" /><div className="relative z-10 max-w-xl px-[14%] pt-[13%]"><div className="flex items-center gap-3"><Mark /><span className="text-4xl font-bold tracking-[-0.04em] text-slate-950">Progress</span></div><h1 className="mt-12 text-6xl font-bold leading-[1.08] tracking-[-0.055em] text-slate-950">Turn your work<br />into progress</h1><p className="mt-6 max-w-lg text-[24px] leading-9 text-slate-600">Set clear objectives, log your work, and see progress across your team and school.</p></div></section><section className="flex items-center justify-center px-5 py-12 sm:px-10"><div className="w-full max-w-[570px] rounded-xl border border-slate-200 bg-white px-7 py-12 shadow-[0_8px_30px_rgba(15,23,42,0.035)] sm:px-12"><div className="text-center"><h1 className="text-[38px] font-bold leading-none tracking-[-0.045em] text-slate-950">Welcome back</h1><p className="mt-3 text-lg text-slate-500">Sign in to your Progress account.</p></div>{params.error && <div className="mt-7 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">That email or password is not right. Please try again.</div>}<form action={login} className="mt-10 space-y-7"><label className="block"><span className="mb-2 block text-base font-medium text-slate-800">Email address</span><span className="relative block"><Icon name="mail" className="pointer-events-none absolute left-4 top-3.5 h-5 w-5 text-slate-500" /><input name="email" type="email" required autoFocus className={`${inputCls} h-[54px] pl-12 text-base`} placeholder="you@school.edu" /></span></label><label className="block"><span className="mb-2 flex items-center justify-between text-base font-medium text-slate-800">Password <span className="text-xs text-slate-500">Ask your administrator to reset it</span></span><PasswordInput /></label><button type="submit" className={`${btnPrimary} h-[56px] w-full text-lg`}>Sign in</button></form><p className="mx-auto mt-9 max-w-sm text-center text-sm leading-6 text-slate-500">Don’t have an account? Contact your school administrator or IT team for access.</p></div></section></div></main>;
}
