import Link from "next/link";
import { getDb } from "@/lib/db";
import { requireSessionUser } from "@/lib/auth";
import { addDailyLog } from "@/lib/actions";
import { todayISO } from "@/lib/rotation";

type Option = { id: number; name: string };
type MonthlyFocus = { id: number; title: string; objective: string };
type Log = { id: number; log_date: string; activity: string; status: string; created_at: string };
type IconName = "calendar" | "link" | "planned" | "recurring" | "reactive" | "clock" | "paperclip" | "check" | "bulb" | "history" | "chevron";

function Icon({ name, className = "" }: { name: IconName; className?: string }) {
  const shapes: Record<IconName, React.ReactNode> = {
    calendar: <><rect x="4" y="5" width="16" height="15" rx="2" /><path d="M8 3v4M16 3v4M4 10h16" /></>,
    link: <><path d="m10 13 4-4M8 17l-1.5 1.5a3 3 0 0 1-4-4L5 12M16 7l1.5-1.5a3 3 0 0 1 4 4L19 12" /></>,
    planned: <><rect x="4" y="5" width="16" height="16" rx="2" /><path d="M8 3v4M16 3v4M8 12h8M8 16h5" /></>,
    recurring: <><path d="M20 7V3l-2 2a8 8 0 0 0-13 3M4 17v4l2-2a8 8 0 0 0 13-3" /></>,
    reactive: <path d="m13 2-9 12h7l-1 8 10-13h-7z" />,
    clock: <><circle cx="12" cy="12" r="8" /><path d="M12 7v5l3 2" /></>,
    paperclip: <path d="m9 12 5-5a3 3 0 1 1 4 4l-7 7a5 5 0 0 1-7-7l7-7" />,
    check: <><circle cx="12" cy="12" r="9" /><path d="m8 12 2.5 2.5L16 9" /></>,
    bulb: <><path d="M9 18h6M10 22h4M8 15c-1.2-1-2-2.6-2-4.5a6 6 0 1 1 12 0c0 1.9-.8 3.5-2 4.5-.7.6-1 1.2-1 2H9c0-.8-.3-1.4-1-2Z" /></>,
    history: <><path d="M3 12a9 9 0 1 0 3-6.7L3 8" /><path d="M3 3v5h5M12 7v5l3 2" /></>,
    chevron: <path d="m9 18 6-6-6-6" />,
  };
  return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.9" strokeLinecap="round" strokeLinejoin="round" className={className} aria-hidden="true">{shapes[name]}</svg>;
}

function Step({ number, title, optional, children, className = "" }: { number: number; title: string; optional?: boolean; children: React.ReactNode; className?: string }) {
  return <div className={`flex gap-4 ${className}`}><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-blue-50 text-sm font-semibold text-blue-600">{number}</span><div className="min-w-0 flex-1"><p className="text-base font-bold text-slate-900">{title} {optional ? <span className="font-normal text-slate-500">(optional)</span> : <span className="text-red-500">*</span>}</p>{children}</div></div>;
}

export default async function DailyPage({ searchParams }: { searchParams: Promise<{ saved?: string }> }) {
  const user = await requireSessionUser();
  const { saved } = await searchParams;
  const db = getDb();
  const today = todayISO();
  const categories = user.template_id ? db.prepare("SELECT id, name FROM task_categories WHERE template_id = ? ORDER BY sort").all(user.template_id) as Option[] : [];
  const departments = user.template_id ? db.prepare("SELECT id, name FROM departments WHERE template_id = ? ORDER BY sort").all(user.template_id) as Option[] : [];
  const monthlyFocus = db.prepare("SELECT mfa.id, mfa.title, mo.title AS objective FROM monthly_focus_areas mfa JOIN monthly_objectives mo ON mo.id = mfa.monthly_objective_id JOIN monthly_plans mp ON mp.id = mo.plan_id WHERE mp.user_id = ? AND mp.status = 'approved' ORDER BY mp.year DESC, mp.month DESC, mo.sort, mfa.sort").all(user.id) as MonthlyFocus[];
  const recent = db.prepare("SELECT id, log_date, activity, status, created_at FROM daily_logs WHERE user_id = ? ORDER BY log_date DESC, id DESC LIMIT 4").all(user.id) as Log[];
  const latestEvidence = saved ? db.prepare("SELECT we.id, we.original_name FROM work_evidence we JOIN work_updates wu ON wu.id = we.work_update_id WHERE wu.user_id = ? ORDER BY we.id DESC LIMIT 1").get(user.id) as { id: number; original_name: string } | undefined : undefined;
  const dateLabel = new Intl.DateTimeFormat("en-GB", { weekday: "long", day: "numeric", month: "long", year: "numeric" }).format(new Date(`${today}T12:00:00`));
  return <div className="space-y-5">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-[40px] font-bold leading-none tracking-[-.045em] text-slate-950">Daily Update</h1><p className="mt-2 text-[17px] text-slate-500">Log what you worked on today.</p></div><div className="flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-medium text-slate-700"><span className="h-5 w-5 text-slate-600"><Icon name="calendar" /></span>{dateLabel}</div><div className="hidden items-center gap-3 rounded-xl bg-slate-100 px-5 py-3 text-sm italic text-slate-500 lg:flex"><span className="h-7 w-7 text-amber-500"><Icon name="bulb" /></span>“Small steps make big progress.”</div></div>
    {saved === "1" && <div className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-800">Your daily update has been saved and is ready for your weekly report.{latestEvidence && <> <Link href={"/evidence/" + latestEvidence.id} className="underline">Open {latestEvidence.original_name}</Link></>}</div>}
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_365px]"><form action={addDailyLog} encType="multipart/form-data" className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-[0_2px_5px_rgba(15,23,42,0.025)]"><input type="hidden" name="log_date" value={today} /><input type="hidden" name="priority" value="Medium" />
      <div className="space-y-7 p-5 sm:p-6">
        <Step number={1} title="What did you work on?"><textarea name="activity" required maxLength={1000} rows={4} placeholder="Describe what you worked on today..." className="mt-3 min-h-24 w-full resize-y rounded-xl border border-slate-200 px-3 py-3 text-sm outline-none placeholder:text-slate-400 focus:border-blue-500" /><p className="mt-1 text-right text-xs text-slate-400">Up to 1,000 characters</p></Step>
        <Step number={2} title="Link to an objective" optional><p className="mt-1 text-sm text-slate-500">Choose an approved focus area when this activity contributes to a monthly objective.</p><div className="mt-3 grid gap-3 md:grid-cols-2"><div className="relative"><span className="absolute left-3 top-3 h-5 w-5 text-slate-500"><Icon name="link" /></span><select name="monthly_focus_area_id" defaultValue="" className="w-full appearance-none rounded-xl border border-slate-200 bg-white py-3 pl-11 pr-10 text-sm text-slate-600 outline-none focus:border-blue-500"><option value="">Operational or unplanned work</option>{monthlyFocus.map((item) => <option key={item.id} value={item.id}>{item.objective} — {item.title}</option>)}</select></div><select name="category_id" defaultValue="" className="rounded-xl border border-slate-200 bg-white px-3 py-3 text-sm text-slate-600 outline-none focus:border-blue-500"><option value="">Role category (optional)</option>{categories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div></Step>
        <Step number={3} title="Work type"><p className="mt-1 text-sm text-slate-500">Choose the type of work this update relates to.</p><div className="mt-3 grid gap-3 md:grid-cols-3"><WorkType icon="planned" title="Planned" text="One-off tasks and projects" value="planned" checked /><WorkType icon="recurring" title="Recurring" text="Regular tasks on a schedule" value="recurring" /><WorkType icon="reactive" title="Reactive" text="Unplanned tasks and issues" value="reactive" /></div></Step>
        <div className="grid gap-6 md:grid-cols-2"><Step number={4} title="Time spent"><div className="relative mt-3"><span className="absolute left-3 top-3 h-5 w-5 text-slate-500"><Icon name="clock" /></span><select name="hours" defaultValue="1" className="w-full appearance-none rounded-xl border border-slate-200 bg-white py-3 pl-11 pr-8 text-sm text-slate-700 outline-none focus:border-blue-500"><option value="0.5">30 minutes</option><option value="1">1 hour</option><option value="2">2 hours</option><option value="3">3 hours</option><option value="4">4 hours</option><option value="8">Full day</option></select></div></Step><Step number={5} title="Status"><div className="relative mt-3"><i className="absolute left-4 top-4 h-3 w-3 rounded-full bg-emerald-500" /><select name="status" defaultValue="In Progress" className="w-full appearance-none rounded-xl border border-slate-200 bg-white py-3 pl-10 pr-8 text-sm text-slate-700 outline-none focus:border-blue-500"><option>In Progress</option><option>Completed</option><option>Pending</option></select></div></Step></div>
        <Step number={6} title="Add evidence" optional><p className="mt-1 text-sm text-slate-500">Add a note, link, or one supporting file. PNG, JPG, PDF, DOC, and DOCX up to 10 MB.</p><textarea name="outcome" rows={2} placeholder="Paste a link, describe the evidence, or add your outcome..." className="mt-3 w-full rounded-xl border border-dashed border-slate-300 px-4 py-4 text-sm outline-none placeholder:text-slate-400 focus:border-blue-500" /><input name="evidence" type="file" accept=".png,.jpg,.jpeg,.pdf,.doc,.docx" className="mt-3 block w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm text-slate-600 file:mr-3 file:rounded-lg file:border-0 file:bg-blue-50 file:px-3 file:py-1.5 file:text-sm file:font-medium file:text-blue-700" /><div className="mt-2 flex flex-wrap gap-3"><select name="department_id" defaultValue="" className="rounded-lg border border-slate-200 px-3 py-2 text-xs text-slate-600"><option value="">Department / section (optional)</option>{departments.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><label className="flex items-center gap-2 text-xs text-slate-500"><input name="followup_required" type="checkbox" className="h-4 w-4 rounded border-slate-300" />Needs a follow-up</label><input name="followup_date" type="date" className="rounded-lg border border-slate-200 px-2 py-1 text-xs text-slate-500" /></div></Step>
      </div>
      <div className="flex justify-end gap-3 border-t border-slate-200 bg-slate-50/70 p-4"><Link href="/" className="rounded-lg border border-slate-200 bg-white px-5 py-3 text-sm font-medium text-slate-700">Cancel</Link><button className="inline-flex items-center gap-2 rounded-lg bg-blue-600 px-6 py-3 text-sm font-semibold text-white shadow-sm hover:bg-blue-700"><span className="h-5 w-5"><Icon name="check" /></span>Save update</button></div>
    </form>
    <aside className="space-y-5"><section className="rounded-xl border border-slate-200 bg-white p-6"><div className="flex items-center gap-3"><span className="h-7 w-7 text-blue-600"><Icon name="bulb" /></span><h2 className="text-xl font-bold text-slate-950">Tips for a great update</h2></div><ul className="mt-6 space-y-5">{[["Be clear and concise", "A few sentences is enough."], ["Link to relevant work", "Connect to a task or objective if applicable."], ["Add evidence", "Notes and links help show progress."], ["Keep it up to date", "Regular updates make reporting easier."]].map(([title, text]) => <li key={title} className="flex gap-3"><span className="h-5 w-5 shrink-0 text-blue-600"><Icon name="check" /></span><span><strong className="block text-sm text-slate-800">{title}</strong><span className="mt-1 block text-sm text-slate-500">{text}</span></span></li>)}</ul></section><section className="rounded-xl border border-slate-200 bg-white p-6"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><span className="h-7 w-7 text-blue-600"><Icon name="history" /></span><h2 className="text-xl font-bold text-slate-950">Recent updates</h2></div><Link href="/weekly" className="text-sm font-medium text-blue-600">View all →</Link></div><div className="mt-5 divide-y divide-slate-100">{recent.length ? recent.slice(0, 3).map((item, index) => <div key={item.id} className="flex gap-3 py-4 first:pt-0"><i className={`mt-1.5 h-3 w-3 shrink-0 rounded-full ${index === 0 ? "bg-emerald-500" : index === 1 ? "bg-blue-600" : "bg-violet-500"}`} /><div className="min-w-0 flex-1"><p className="text-sm font-medium leading-5 text-slate-800">{item.activity}</p><p className="mt-1 text-xs text-slate-400">{item.log_date} · {item.status}</p></div></div>) : <p className="py-5 text-sm text-slate-500">Your saved updates will appear here.</p>}</div></section></aside></div>
  </div>;
}

function WorkType({ icon, title, text, value, checked = false }: { icon: "planned" | "recurring" | "reactive"; title: string; text: string; value: "planned" | "recurring" | "reactive"; checked?: boolean }) {
  return <label className="relative flex min-h-22 cursor-pointer gap-3 rounded-xl border border-slate-200 bg-white p-4 has-[:checked]:border-blue-600 has-[:checked]:bg-blue-50/40"><input className="sr-only" type="radio" name="work_type" value={value} defaultChecked={checked} /><span className={icon === "reactive" ? "h-7 w-7 text-amber-500" : "h-7 w-7 text-blue-600"}><Icon name={icon} /></span><span><strong className="block text-sm text-slate-800">{title}</strong><span className="mt-1 block text-xs leading-4 text-slate-500">{text}</span></span><i className="absolute right-3 top-3 h-5 w-5 rounded-full border-2 border-slate-300" /></label>;
}
